export const causesData = [
    {
      id: 1, 
      name: "Ocean Cleanup",
      description: "Fighting ocean plastic pollution",
      longDescription: `The Ocean Cleanup is a non-profit organization developing advanced technologies to rid the world's oceans of plastic. They aim to clean up 90% of floating ocean plastic pollution through their innovative cleanup systems.
    
Every year, millions of tons of plastic enter the oceans primarily from rivers and coastal areas. The floating plastic accumulates in five ocean garbage patches, with the largest one being the Great Pacific Garbage Patch.
    
Their cleanup approach involves two main strategies: cleaning up existing pollution in the ocean and intercepting plastic before it reaches the oceans through rivers. Their systems are designed to be environmentally friendly, safe for marine life, and powered by natural oceanic forces.`,
      imageSrc: "https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg",
      category: "Environment",
      fundedPercentage: 76,
      goal: 500000,
      raised: 380000,
      donors: 1245,
      daysLeft: 23,
      website: "https://theoceancleanup.com/",
      updates: [ { id: 1, date: "2025-05-01", title: "New cleanup vessel launched", content: "We're excited to announce that our new cleanup vessel has been deployed in the Great Pacific Garbage Patch." } ],
      walletAddress: '0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B',
      isActive: true,
      featured: false,
    },
    {
      id: 2, 
      name: "Reforestation Project",
      description: "Planting trees in deforested areas",
      longDescription: `The Reforestation Project is dedicated to restoring forests around the globe by planting trees. This helps to combat climate change, restore biodiversity, and provide sustainable livelihoods for local communities.`,
      imageSrc: "https://images.pexels.com/photos/957024/forest-trees-perspective-bright-957024.jpeg",
      category: "Climate Action",
      fundedPercentage: 83,
      goal: 200000,
      raised: 166000,
      donors: 850,
      daysLeft: 45,
      website: "https://onetreeplanted.org/",
      updates: [ { id: 1, date: "2025-05-10", title: "1 Million Trees Planted!", content: "We've reached a major milestone thanks to your support!" } ],
      walletAddress: '0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5',
      isActive: true,
      featured: true,
    },
    {
      id: 3, 
      name: "Clean Water Initiative",
      description: "Providing clean water to rural communities",
      longDescription: `The Clean Water Initiative works to bring clean and safe drinking water to communities in developing countries. Access to clean water improves health, increases school attendance, and empowers women and children.`,
      imageSrc: "https://images.pexels.com/photos/1552941/pexels-photo-1552941.jpeg",
      category: "Humanitarian",
      fundedPercentage: 65,
      goal: 150000,
      raised: 97500,
      donors: 980,
      daysLeft: 50,
      website: "https://www.charitywater.org/",
      updates: [],
      walletAddress: '0x8e23d11b519a4e2d443a6759034f71f1f2e2f3d6',
      isActive: true,
      featured: false,
    },
    {
      id: 4, 
      name: "Wildlife Conservation",
      description: "Protecting endangered species",
      longDescription: `The Wildlife Conservation fund is dedicated to protecting endangered species and their habitats. They work on anti-poaching initiatives, habitat restoration, and community outreach programs to ensure a future for wildlife.`,
      imageSrc: "https://images.pexels.com/photos/247431/pexels-photo-247431.jpeg",
      category: "Wildlife",
      fundedPercentage: 42,
      goal: 300000,
      raised: 126000,
      donors: 450,
      daysLeft: 80,
      website: "https://www.worldwildlife.org/",
      updates: [],
      walletAddress: '0x9d4a1f2e6b7c8d9e0f1a2b3c4d5e6f7g8h9i0j1k',
      isActive: true,
      featured: false,
    },
    {
      id: 5, 
      name: "Education For All",
      description: "Providing quality education to underprivileged children",
      longDescription: `Education For All aims to break the cycle of poverty by providing quality education to children in underserved communities. They build schools, provide learning materials, and support teachers.`,
      imageSrc: "https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg",
      category: "Education",
      fundedPercentage: 88,
      goal: 100000,
      raised: 88000,
      donors: 1500,
      daysLeft: 15,
      website: "https://www.unicef.org/education",
      updates: [],
      walletAddress: '0x1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t',
      isActive: true,
      featured: true,
    },
    {
      id: 6, 
      name: "Hunger Relief",
      description: "Providing meals to those in need",
      longDescription: `The Hunger Relief fund provides nutritious meals to families and individuals facing food insecurity. They operate food banks, soup kitchens, and emergency food distribution programs.`,
      imageSrc: "https://images.pexels.com/photos/6995212/pexels-photo-6995212.jpeg",
      category: "Humanitarian",
      fundedPercentage: 71,
      goal: 250000,
      raised: 177500,
      donors: 2100,
      daysLeft: 30,
      website: "https://www.wfp.org/",
      updates: [],
      walletAddress: '0x2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u',
      isActive: true,
      featured: false,
    },
    {
      id: 7, 
      name: "Renewable Energy",
      description: "Supporting clean energy projects",
      longDescription: `This fund supports the development and implementation of renewable energy projects, such as solar and wind farms, to combat climate change and provide sustainable energy to communities.`,
      imageSrc: "https://images.pexels.com/photos/356036/pexels-photo-356036.jpeg",
      category: "Climate Action",
      fundedPercentage: 59,
      goal: 750000,
      raised: 442500,
      donors: 300,
      daysLeft: 120,
      website: "https://www.greenpeace.org/international/act/renewable-energy/",
      updates: [],
      walletAddress: '0x3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v',
      isActive: false,
      featured: false,
    },
    {
      id: 8, 
      name: "Healthcare Access",
      description: "Expanding medical services to remote areas",
      longDescription: `Healthcare Access works to improve the health and well-being of people in remote and underserved areas by providing essential medical services, supplies, and training for local healthcare workers.`,
      imageSrc: "https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg",
      category: "Healthcare",
      fundedPercentage: 67,
      goal: 400000,
      raised: 268000,
      donors: 1100,
      daysLeft: 60,
      website: "https://www.doctorswithoutborders.org/",
      updates: [],
      walletAddress: '0x4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w',
      isActive: true,
      featured: true,
    }
];
